spring:
  application:
    name: payments

server:
  port: 9092
  servlet:
    contextPath: /payments

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'