server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bookingModule
          uri: lb://BOOKING
          predicates:
            - Path=/hotel/booking/**
        - id: paymentModule
          uri: lb://PAYMENTS
          predicates:
            - Path=/payment/**
management:
  info:
    git:
      mode: full

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka