spring:
  application:
    name: booking

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9091
  servlet:
    contextPath: /booking

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true